annotations:
  artifacthub.io/changes: |
    - kind: fix
      description: Remove '$' from the password validation schema for RabbitMQ
apiVersion: v2
appVersion: 1.0.1
dependencies:
- condition: postgresql.install
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: ~10.15.1
- condition: redis.install
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: ~15.7.2
- condition: rabbitmq.install
  name: rabbitmq
  repository: https://charts.bitnami.com/bitnami
  version: ~8.26.0
description: Rasa X Helm chart for Kubernetes / Openshift
home: https://github.com/RasaHQ/rasa-x-helm
icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqZPsa-h0ilYPCFaQmf21MFMyVH7oyvrfnJHwvGOJVlMIeTiakBJTSwGd2cDFcF5AsEiY&usqp=CAU
keywords:
- Rasa
- AI Assistants
- Chatbot
- Rasa X
maintainers:
- email: tom@rasa.com
  name: tmbo
  url: https://rasa.com
name: rasa-x
version: 4.5.4
